### ISSUE TITLE
Partial loading and interpolate select do not appear to work together. And there may be issues with partial loading with using a float.

### ISSUE THREAD

**Issue by manauref** [ammarhakim/postgkyl#21]
Given two files, I want to plot their difference at x=-7, which is in the first cell of the datasets. So I can use
```
pgkyl fileA.bp fileB.bp interp sel --z0 -7. ev 'f[0] f[1] -' pl
```
which works fine. But if one wants to use partial loading to just load the data in the first cell and then plot at x=-7 via
```
pgkyl --z0 0 fileA.bp fileB.bp interp sel --z0 -7. ev 'f[0] f[1] -' pl
```
then the following error shows up:

anaconda3/lib/python3.8/site-packages/postgkyl/output/plot.py", line 90, in plot
    raise Exception('Only 1D and 2D plots are currently supported')

Also, I think partial loading with a float might be off. I thought
```
pgkyl --z0 -7. ...
```
was supposed to load a cell which is "closest" (whatever that means) to this point. But either it loads some other cell, or it throws an error like 

anaconda3/lib/python3.8/site-packages/postgkyl/utils/idxParser.py", line 18, in _findCellIndex
    raise TypeError("The index value is float but the 'array' from which to select the neares value is not specified.")

**Comment by JunoRavin** [comment]
It is my understanding that the --z0 0 must follow the file names. 

Also, I think partial loading only works with integers (@pcagas correct me if I am wrong here, this is my understanding) because partial loading is loading the actual indices of the data structure (it is not reading in the grid and finding the closest value on the grid to the float you have specified).

Thus, after you call interpolate, you are generating the same higher dimensional dataset because you are creating a uniform mesh within a single cell. If you do partial loading you must interpolate and then select again, as you are currently doing.

**Comment by manauref** [comment]
For multiple data sets you can follow ``pgkyl`` with ``--z# <integer>``,
and it should do partial loading for the subsequent datasets. Or you could
place multiple copies of ``--z# <integer>`` after every dataset if you need
the finger exercise.

I thought I had read somewhere that partial loading with ``--z# <float>``
would load the cell closest to that point, but I could be wrong. Certainly
https://gkeyll.readthedocs.io/en/latest/postgkyl/loading.html does not seem
to mention such option.

**Comment by JunoRavin** [comment]
First of all, neat! Did not realize (or forgot..) that was the default behavior now at the command line that we could do partial loads on multiple files by just including the --z# before the files.

It seems like the bug might be in select and not in partial loading. I just tried to do the first thing you did @manauref where you do a partial load with an integer, then select the closest float, on 2D data, and I can't even do an info on the data. The select works if I specify an integer (0, 1, or 2 after interpolating piecewise quadratic data) but throws a ValueError

"zero-size array to reduction operation minimum which has no identity"

for any float I specify, including floats I know are within the bounds of the down-sampled array (I get this same ValueError if I pass an integer to select that's outside the range like 4 or 10).

**Comment by pcagas** [comment]
All this is really on me because I didn't update the documentation yet. Previously, the partial load flag was a parameter of the base (pgkyl) command the same as the file names themselves (with -f). After the update, each file name you specify is technically a command so any flag that follows it applies only to that one file name. However, I did introduce some global parameters that are still specified as parameters to pgkyl and then apply all the datasets. Note that if you specify the same parameter for one file, this takes precedent and overwrites the global setting. Pgkyl should write a warning though.

Partial loading never worked with floats. This happens before the data are loaded so pgkyl has no information about the grid yet. It can only use the adios capabilities to partially load some indices.

Doing select with float should return the closest value. However, this is not the first time that somebody reported a problem. It seems like this does not work if the specified float is out of the range. This is not intended and needs to be fixed.

**Comment by manauref** [comment]
Petr if you fix the partial loading/sel interaction I can take care of the documentation.

I don't have a strong opinion about partial loading with a float at the moment. I'll leave it up to you guys.
