### ISSUE TITLE
List command for files with several datasets/varnames

### ISSUE THREAD

**Issue by nmandell** [ammarhakim/postgkyl#27]
We have some output files which contain several datasets, each with their own varname. For example, in GK, we have an `*_allGeo_0.bp` file, which contains several geometry-related quantities. A particular quantity can be accessed using the `-d` flag, e.g. `pgkyl '*_allGeo_0.bp' -d bmag info`. 

Perhaps the `listoutputs` command can be extended for this purpose, so that it will show all of the available varnames/datasets in such a file. This could be used as
```
> pgkyl '*_allGeo_0.bp' list
bdriftX 
bmag    
cmag    
bmagInv 
bdriftY 
gxx     
gxy     
gyy
```

**Comment by manauref** [comment]
Alternatively this could be folded into `pgkyl info` so that `pgkyl
sim_allGeo_0.bp info` without the `-d dataset` simply lists all the
datasets? not sure. We also need to keep in mind how these things will work
when we have multiple blocks and we have things like

block1/bmag
block1/bdriftY
...
block2/bmag
block2/bdriftY
...
etc

**Comment by manauref** [comment]
Also, I forgot to mention that this can be accomplished with `bpls`
```
bpls <simName>_allGeo_0.bp
```

**Comment by pcagas** [comment]
At this point, specifying a file in the postgkyl chain loads the file (this might change in the future). So this functionality of listing varnames after the file is loaded doesn't currently make much sense to me. I can easily create a new command that lists varnames for a specified file but that duplicates the functionality of `bpls` that @manauref mentioned.

I think it is currently cleaner to keep it as it is but I can be convinced otherwise.

**Comment by ammarhakim** [comment]
This old issue was closed without any resolution. The multi-data file are not readable from pgkyl and I can't find the list of data-sets in the file. Using bpls is not an option as we can't rely on any external tools like that. What happens if the multi-data files are say native G0 files in the future, or Flash files?

What I recommend is we extend the info command to handle this. Info could list all files and print further info on each of them. This would remove the dependency on bpls which may not be installed and anyway the file may not be a BP file to start with.

The fact that pgkyl barfs on Gkeyll generated output is not a good look for us. We should never fail on any BP or Gkyl file we ourselves generate. Even if we just handle info for some files that is enough.

**Comment by pcagas** [comment]
A draft with a solution to this issue in the `loading_revamp` revamp branch (also currently a PR draft #111).

The biggest change under the hood is that loading a dataset header/attributes is now split from the loading of the actual data. This allows for example to call `info` on a dataset without fully loading it, although with limited results:
```
$ pgkyl rt-two-stream-p2_elc_20.bp info                               (py311) 
(default#0)
├─ Time: 5.000145e+01
├─ Frame: 20
├─ Number of components: 8
├─ Number of dimensions: 2
├─ Grid: (uniform)
│  ├─ Dim 0: Num. cells: 64; Lower: -6.283185e+00; Upper: 6.283185e+00
│  └─ Dim 1: Num. cells: 32; Lower: -6.000000e+00; Upper: 6.000000e+00
├─ Maximum: 1.733686e+00 at (46, 16) component 0
├─ Minimum: -8.160604e-01 at (18, 14) component 2
├─ DG info:
│  ├─ Polynomial Order: 2
│  └─ Basis Type: serendipity (modal)
├─ Created with Gkeyll:
│  ├─ Changeset: 9663ea594e80
│  └─ Build Date: Jun 14 2023 10:04:32
├─ charge: -1
├─ mass: 1
```
```
$ pgkyl rt-two-stream-p2_elc_20.bp --no-load info                        (py311) 
(default#0)
├─ Time: 5.000145e+01
├─ Frame: 20
├─ Number of components: 0
├─ Number of dimensions: 2
├─ Grid: (uniform)
│  ├─ Dim 0: Num. cells: 64; Lower: -6.283185e+00; Upper: 6.283185e+00
│  └─ Dim 1: Num. cells: 32; Lower: -6.000000e+00; Upper: 6.000000e+00
├─ DG info:
│  ├─ Polynomial Order: 2
│  └─ Basis Type: serendipity (modal)
├─ Created with Gkeyll:
│  ├─ Changeset: 9663ea594e80
│  └─ Build Date: Jun 14 2023 10:04:32
├─ charge: -1
├─ mass: 1
```
Note the minima and maxima, which require loading the data, are missing.

This change also allows the `info` command to show the available BP variable names. See, a dummy test case:
```
$ pgkyl test.bp --no-load info                                           (py311) 
(default#0)
├─ Time: 5.000145e+01
├─ Number of components: 0
├─ Number of dimensions: 2
├─ Grid: (uniform)
│  ├─ Dim 0: Num. cells: 64; Lower: -6.283185e+00; Upper: 6.283185e+00
│  └─ Dim 1: Num. cells: 32; Lower: -6.000000e+00; Upper: 6.000000e+00
├─ var_names: 'TestName', 'time'
```

Finally, @ammarhakim is right that the Gkeyll-generated outputs should never fail. Therefore I have added a `click` prompt (https://click.palletsprojects.com/en/8.1.x/prompts/) to ask for a variable name if the standard `CartGridField` is not found.
```
$ pgkyl test.bp info                                                     (py311) 
Variable name 'CartGridField' is not available, please select from the available ones: 'TestName', 'time': 
```

Some testing is still required before the PR can be submitted.

**Comment by pcagas** [comment]
This work can directly enable future enhancements like better partial loading.
